# Generated by Django 3.1.4 on 2020-12-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201225_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(default='unknown', max_length=10),
        ),
    ]
