# Generated by Django 3.1.4 on 2020-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(default='unknown', max_length=49),
        ),
    ]
